### ISSUE TITLE
compiling errors. 

### ISSUE THREAD

**Issue by AKA-TiTAN** [vbawol/DayZhiveEpoch#10]
------ Build started: Project: HiveLib, Configuration: Release Win32 ------
  fatal: Not a git repository (or any of the parent directories): .git
  Traceback (most recent call last):
    File "C:\DayZhiveEpoch\Hive\Source\HiveLib\version_gen.py", line 8, in <module>
      _out.write(_in.read().replace("%GIT_VERSION%", version))
  TypeError: expected bytes, bytearray or buffer compatible object
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(124,5): error MSB3073: The command "python C:\DayZhiveEpoch\Hive\Source\HiveLib\version_gen.py C:\DayZhiveEpoch\Hive\Source\HiveLib\Version.cpp.template C:\DayZhiveEpoch\Hive\Source\HiveLib\Version.cpp

**Comment by fank** [comment]
Did you cloned the repo via "git clone" or did you downloaded it via zip?
Because the log can't find a git repo.

**Comment by AKA-TiTAN** [comment]
figured it out thanks
