### ISSUE TITLE
CHILD:999 can't handle big values (like UID)

### ISSUE THREAD

**Issue by kikyou2** [vbawol/DayZhiveEpoch#4]
Everytime you try to use the CHILD:999 function to stream the UID from database to server, always same value is incoming "2147483647".

I'm thinking here is a too small datatype used to store the value. 

For more information visit

http://opendayz.net/threads/possible-to-publish-to-new-table-in-database.14642/#post-80537

**Comment by vbawol** [comment]
999 should not be used as it is insecure, use our new dll and the custom 500-505 calls.
